<?php
/**
 * User: Leonardo
 * Date: 17/11/2016
 * Time: 17:41
 */

namespace Sistema\Repositories;


use Prettus\Repository\Eloquent\BaseRepository;
use Sistema\Entities\Project;
use Sistema\Presenters\ProjectPresenter;

class ProjectRepositoryEloquent extends BaseRepository implements ProjectRepository
{
    
    public function model()
    {
        return Project::class;
    }
    
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
    
    /* Verifica se o usuário é dono do Projeto */

    public function isOwner($projectId, $userId)
    {
        if(count($this->findWhere(['id' => $projectId, 'owner_id' => $userId]))){
            return true;
        }
        return false;
    }

    public function hasMember($projectId, $memberId)
    {
        $project = $this->find($projectId);

        foreach ($project->members as $member){
            if($member->id == $memberId){
                return true;
            }
        }
        return false;
    }
    
    public function presenter()
    {
        return ProjectPresenter::class;
    }


}