<?php
/**
 * User: Leonardo
 * Date: 17/11/2016
 * Time: 17:41
 */

namespace Sistema\Repositories;


use Prettus\Repository\Eloquent\BaseRepository;
use Sistema\Entities\Project;

class ProjectRepositoryEloquent extends BaseRepository implements ProjectRepository
{
    
    public function model()
    {
        return Project::class;
    }
    
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}